### ISSUE TITLE
I cannot open build tasks by ctrl+shift+b because of this extension

### ISSUE THREAD

**Issue by rockingdice** [microsoft/vscode-java-dependency#720] opened 2023-03-03 01:19 UTC
Type: <b>Bug</b>

turn on this extension and use hotkeys to bring up the task menu, it will stuck at the 'Fetching Tasks' phase.

Extension version: 0.21.1
VS Code version: Code 1.76.0 (Universal) (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:23:45.993Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|6, 6, 5|
|Memory (System)|16.00GB (2.63GB free)|
|Process Argv|--crash-reporter-id d2743afe-0b94-4c78-b00e-97554cafa983|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewvextcfv2:30669238
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30662994
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
vsctsb:30662444
pythonb192:30669360

```

</details>

**Comment by jdneo** [comment] 2023-03-03 01:51
We just merged a potential fix for this issue yesterday. Could you try this vsix

[vscode-java-test-0.38.2023030203.vsix.zip](https://github.com/microsoft/vscode-java-dependency/files/10877391/vscode-java-test-0.38.2023030203.vsix.zip)

And let us know if the problem get resolved?

**Comment by jdneo** [comment] 2023-03-03 01:54
We merged a potential [fix](https://github.com/microsoft/vscode-java-dependency/pull/719) for this issue yesterday. Could you try install

[vscode-java-dependency-0.21.2023030301.vsix.zip](https://github.com/microsoft/vscode-java-dependency/files/10877412/vscode-java-dependency-0.21.2023030301.vsix.zip)


And let us know if the problem get resolved?

**Comment by rockingdice** [comment] 2023-03-04 00:26
@jdneo sorry it's not working after installing the fix. Is this a new issue? I didn't have any issues several days ago. I just realized my old pc cannot open the tasks menu too with this extension.

**Comment by rockingdice** [comment] 2023-03-04 00:39
* It's not stuck but extremely slow on my old pc. It's downloading the necessary Gradle dependencies. After it's done the menu shows up. 
So I wonder if it should not make the users wait because we don't always work with Java projects. There are a lot of tasks too.
On my new pc, the menu won't show up anymore. Because there's no JDK installed.

**Comment by jdneo** [comment] 2023-03-06 02:44
Ok, so it turns out that waiting for the LS being ready is not ideal.

We should just catch the error when we sending the requests to LS but LS is not ready.

@CsCherrYY is working on it now.

**Closed** 2023-03-08 09:37 UTC
Labels: bug

**Comment by jdneo** [comment] 2023-03-09 02:13
Hi @rockingdice
It would be great if you could try this bit with the new fix, and let us know if the problem is fixed.
[vscode-java-dependency-0.21.2023030900.vsix.zip](https://github.com/microsoft/vscode-java-dependency/files/10926994/vscode-java-dependency-0.21.2023030900.vsix.zip)

Thank you!
