### ISSUE TITLE
Why  it doesn't  detect Maven Project ?

### ISSUE THREAD

**Issue by quanllong** [microsoft/vscode-java-dependency#733] opened 2023-04-07 15:46 UTC
The project can run with maven jar, but it doesn't detect by extension and noting displayed in the "Java Projects ".
 I hope to display the project info in "Java Projects ". 
How can I fix it ?

![image](https://user-images.githubusercontent.com/37549357/230637722-0dcd1e0a-bb3d-4c8d-a8f3-801b3be60f2d.png)

**Comment by quanllong** [comment] 2023-04-07 16:12
Any advice or comment ?  :)

**Comment by jdneo** [comment] 2023-04-10 01:45
Usually this means that the project is failed to import. Could you please check:

1. If there is any error reported in the `PROBLEM` panel?
2. If there is any error in the logs. See: https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging

---

BTW, as an enhancement, the extension should report import errors if it happens. This is tracked by https://github.com/microsoft/vscode-java-dependency/issues/580

**Comment by quanllong** [comment] 2023-04-10 08:07
Thanks for your help~ 
Actually I found an error reported in the `PROBLEM` panel and solved. 
The pannel seems not  arrestive, so I missed it at the beginning.
Also I think the enhancement that you mentioned is helpful

**Comment by jdneo** [comment] 2023-04-10 08:13
I see. the error exposure issue should be addressed in the next version of the extension.

I'm closing this issue now since the problem is gone on your side and let track the exposure issue in https://github.com/microsoft/vscode-java-dependency/issues/580

**Closed by jdneo** 2023-04-10 08:13 UTC
Labels: duplicate
